spring:
  application:
    name: twitter
  datasource:
    url: jdbc:mysql://localhost:3306/twitterdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev
    password: dev123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: twitter-clone-secret-key-must-be-at-least-32-characters-long
  access-token-expiration: 3600000
