spring:
  application:
    name: twitter
  datasource:
    url: jdbc:mysql://localhost:3306/twitterdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev
    password: dev123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
